/*
 * MIT License
 *
 * Copyright (c) 2024 emexlab
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef EMEX64_KEYBOARD_H
#define EMEX64_KEYBOARD_H

#include <stdint.h>

typedef enum: uint8_t {
    kEmexKeyPhysEsc,
    kEmexKeyPhysF1,
    kEmexKeyPhysF2,
    kEmexKeyPhysF3,
    kEmexKeyPhysF4,
    kEmexKeyPhysF5,
    kEmexKeyPhysF6,
    kEmexKeyPhysF7,
    kEmexKeyPhysF8,
    kEmexKeyPhysF9,
    kEmexKeyPhysF10,
    kEmexKeyPhysF11,
    kEmexKeyPhysF12,
    kEmexKeyPhysGrave,
    kEmexKeyPhys1,
    kEmexKeyPhys2,
    kEmexKeyPhys3,
    kEmexKeyPhys4,
    kEmexKeyPhys5,
    kEmexKeyPhys6,
    kEmexKeyPhys7,
    kEmexKeyPhys8,
    kEmexKeyPhys9,
    kEmexKeyPhys0,
    kEmexKeyPhysMinus,
    kEmexKeyPhysEqual,
    kEmexKeyPhysBackspace,
    kEmexKeyPhysTab,
    kEmexKeyPhysQ,
    kEmexKeyPhysW,
    kEmexKeyPhysE,
    kEmexKeyPhysR,
    kEmexKeyPhysT,
    kEmexKeyPhysY,
    kEmexKeyPhysU,
    kEmexKeyPhysI,
    kEmexKeyPhysO,
    kEmexKeyPhysP,
    kEmexKeyPhysLeftBracket,
    kEmexKeyPhysRightBracket,
    kEmexKeyPhysBackslash,
    kEmexKeyPhysCapsLock,
    kEmexKeyPhysA,
    kEmexKeyPhysS,
    kEmexKeyPhysD,
    kEmexKeyPhysF,
    kEmexKeyPhysG,
    kEmexKeyPhysH,
    kEmexKeyPhysJ,
    kEmexKeyPhysK,
    kEmexKeyPhysL,
    kEmexKeyPhysSemicolon,
    kEmexKeyPhysQuote,
    kEmexKeyPhysEnter,
    kEmexKeyPhysLeftShift,
    kEmexKeyPhysZ,
    kEmexKeyPhysX,
    kEmexKeyPhysC,
    kEmexKeyPhysV,
    kEmexKeyPhysB,
    kEmexKeyPhysN,
    kEmexKeyPhysM,
    kEmexKeyPhysComma,
    kEmexKeyPhysPeriod,
    kEmexKeyPhysSlash,
    kEmexKeyPhysRightShift,
    kEmexKeyPhysLeftCtrl,
    kEmexKeyPhysLeftGUI,
    kEmexKeyPhysLeftAlt,
    kEmexKeyPhysSpace,
    kEmexKeyPhysRightAlt,
    kEmexKeyPhysRightGUI,
    kEmexKeyPhysMenu,
    kEmexKeyPhysRightCtrl,
    kEmexKeyPhysInsert,
    kEmexKeyPhysDelete,
    kEmexKeyPhysHome,
    kEmexKeyPhysEnd,
    kEmexKeyPhysPageUp,
    kEmexKeyPhysPageDown,
    kEmexKeyPhysArrowUp,
    kEmexKeyPhysArrowLeft,
    kEmexKeyPhysArrowDown,
    kEmexKeyPhysArrowRight,
    kEmexKeyPhysNumLock,
    kEmexKeyPhysNumpadDivide,
    kEmexKeyPhysNumpadMultiply,
    kEmexKeyPhysNumpadMinus,
    kEmexKeyPhysNumpadPlus,
    kEmexKeyPhysNumpadEnter,
    kEmexKeyPhysNumpad1,
    kEmexKeyPhysNumpad2,
    kEmexKeyPhysNumpad3,
    kEmexKeyPhysNumpad4,
    kEmexKeyPhysNumpad5,
    kEmexKeyPhysNumpad6,
    kEmexKeyPhysNumpad7,
    kEmexKeyPhysNumpad8,
    kEmexKeyPhysNumpad9,
    kEmexKeyPhysNumpad0,
    kEmexKeyPhysNumpadDot,
    kEmexKeyPhysPrintScreen,
    kEmexKeyPhysScrollLock,
    kEmexKeyPhysPause,
    kEmexKeyPhysUnknown
} kEmexKeyPhys;

typedef struct {
    uint8_t length;
    uint8_t data[4];
} ps2_scancode_t;

static const ps2_scancode_t kEmexKeyPhysToPS2Set1[] = {
    [kEmexKeyPhysEsc] = {1, {0x01}},
    [kEmexKeyPhysF1] = {1, {0x3B}},
    [kEmexKeyPhysF2] = {1, {0x3C}},
    [kEmexKeyPhysF3] = {1, {0x3D}},
    [kEmexKeyPhysF4] = {1, {0x3E}},
    [kEmexKeyPhysF5] = {1, {0x3F}},
    [kEmexKeyPhysF6] = {1, {0x40}},
    [kEmexKeyPhysF7] = {1, {0x41}},
    [kEmexKeyPhysF8] = {1, {0x42}},
    [kEmexKeyPhysF9] = {1, {0x43}},
    [kEmexKeyPhysF10] = {1, {0x44}},
    [kEmexKeyPhysF11] = {1, {0x57}},
    [kEmexKeyPhysF12] = {1, {0x58}},
    [kEmexKeyPhysGrave] = {1, {0x29}},
    [kEmexKeyPhys1] = {1, {0x02}},
    [kEmexKeyPhys2] = {1, {0x03}},
    [kEmexKeyPhys3] = {1, {0x04}},
    [kEmexKeyPhys4] = {1, {0x05}},
    [kEmexKeyPhys5] = {1, {0x06}},
    [kEmexKeyPhys6] = {1, {0x07}},
    [kEmexKeyPhys7] = {1, {0x08}},
    [kEmexKeyPhys8] = {1, {0x09}},
    [kEmexKeyPhys9] = {1, {0x0A}},
    [kEmexKeyPhys0] = {1, {0x0B}},
    [kEmexKeyPhysMinus] = {1, {0x0C}},
    [kEmexKeyPhysEqual] = {1, {0x0D}},
    [kEmexKeyPhysBackspace] = {1, {0x0E}},
    [kEmexKeyPhysTab] = {1, {0x0F}},
    [kEmexKeyPhysQ] = {1, {0x10}},
    [kEmexKeyPhysW] = {1, {0x11}},
    [kEmexKeyPhysE] = {1, {0x12}},
    [kEmexKeyPhysR] = {1, {0x13}},
    [kEmexKeyPhysT] = {1, {0x14}},
    [kEmexKeyPhysY] = {1, {0x15}},
    [kEmexKeyPhysU] = {1, {0x16}},
    [kEmexKeyPhysI] = {1, {0x17}},
    [kEmexKeyPhysO] = {1, {0x18}},
    [kEmexKeyPhysP] = {1, {0x19}},
    [kEmexKeyPhysLeftBracket] = {1, {0x1A}},
    [kEmexKeyPhysRightBracket] = {1, {0x1B}},
    [kEmexKeyPhysBackslash] = {1, {0x2B}},
    [kEmexKeyPhysCapsLock] = {1, {0x3A}},
    [kEmexKeyPhysA] = {1, {0x1E}},
    [kEmexKeyPhysS] = {1, {0x1F}},
    [kEmexKeyPhysD] = {1, {0x20}},
    [kEmexKeyPhysF] = {1, {0x21}},
    [kEmexKeyPhysG] = {1, {0x22}},
    [kEmexKeyPhysH] = {1, {0x23}},
    [kEmexKeyPhysJ] = {1, {0x24}},
    [kEmexKeyPhysK] = {1, {0x25}},
    [kEmexKeyPhysL] = {1, {0x26}},
    [kEmexKeyPhysSemicolon] = {1, {0x27}},
    [kEmexKeyPhysQuote] = {1, {0x28}},
    [kEmexKeyPhysEnter] = {1, {0x1C}},
    [kEmexKeyPhysLeftShift] = {1, {0x2A}},
    [kEmexKeyPhysZ] = {1, {0x2C}},
    [kEmexKeyPhysX] = {1, {0x2D}},
    [kEmexKeyPhysC] = {1, {0x2E}},
    [kEmexKeyPhysV] = {1, {0x2F}},
    [kEmexKeyPhysB] = {1, {0x30}},
    [kEmexKeyPhysN] = {1, {0x31}},
    [kEmexKeyPhysM] = {1, {0x32}},
    [kEmexKeyPhysComma] = {1, {0x33}},
    [kEmexKeyPhysPeriod] = {1, {0x34}},
    [kEmexKeyPhysSlash] = {1, {0x35}},
    [kEmexKeyPhysRightShift] = {1, {0x36}},
    [kEmexKeyPhysLeftCtrl] = {1, {0x1D}},
    [kEmexKeyPhysLeftGUI] = {2, {0xE0, 0x5B}},
    [kEmexKeyPhysLeftAlt] = {1, {0x38}},
    [kEmexKeyPhysSpace] = {1, {0x39}},
    [kEmexKeyPhysRightAlt] = {2, {0xE0, 0x38}},
    [kEmexKeyPhysRightGUI] = {2, {0xE0, 0x5C}},
    [kEmexKeyPhysMenu] = {2, {0xE0, 0x5D}},
    [kEmexKeyPhysRightCtrl] = {2, {0xE0, 0x1D}},
    [kEmexKeyPhysInsert] = {2, {0xE0, 0x52}},
    [kEmexKeyPhysDelete] = {2, {0xE0, 0x53}},
    [kEmexKeyPhysHome] = {2, {0xE0, 0x47}},
    [kEmexKeyPhysEnd] = {2, {0xE0, 0x4F}},
    [kEmexKeyPhysPageUp] = {2, {0xE0, 0x49}},
    [kEmexKeyPhysPageDown] = {2, {0xE0, 0x51}},
    [kEmexKeyPhysArrowUp] = {2, {0xE0, 0x48}},
    [kEmexKeyPhysArrowLeft] = {2, {0xE0, 0x4B}},
    [kEmexKeyPhysArrowDown] = {2, {0xE0, 0x50}},
    [kEmexKeyPhysArrowRight] = {2, {0xE0, 0x4D}},
    [kEmexKeyPhysNumLock] = {1, {0x45}},
    [kEmexKeyPhysNumpadDivide] = {2, {0xE0, 0x35}},
    [kEmexKeyPhysNumpadMultiply] = {1, {0x37}},
    [kEmexKeyPhysNumpadMinus] = {1, {0x4A}},
    [kEmexKeyPhysNumpadPlus] = {1, {0x4E}},
    [kEmexKeyPhysNumpadEnter] = {2, {0xE0, 0x1C}},
    [kEmexKeyPhysNumpad1] = {1, {0x4F}},
    [kEmexKeyPhysNumpad2] = {1, {0x50}},
    [kEmexKeyPhysNumpad3] = {1, {0x51}},
    [kEmexKeyPhysNumpad4] = {1, {0x4B}},
    [kEmexKeyPhysNumpad5] = {1, {0x4C}},
    [kEmexKeyPhysNumpad6] = {1, {0x4D}},
    [kEmexKeyPhysNumpad7] = {1, {0x47}},
    [kEmexKeyPhysNumpad8] = {1, {0x48}},
    [kEmexKeyPhysNumpad9] = {1, {0x49}},
    [kEmexKeyPhysNumpad0] = {1, {0x52}},
    [kEmexKeyPhysNumpadDot] = {1, {0x53}},
    [kEmexKeyPhysPrintScreen] = {4, {0xE0, 0x2A, 0xE0, 0x37}},
    [kEmexKeyPhysScrollLock] = {1, {0x46}},
    [kEmexKeyPhysPause] = {3, {0xE1, 0x1D, 0x45}},
    [kEmexKeyPhysUnknown] = {0, {0}},
};

#endif /* EMEX64_KEYBOARD_H */
